FROM n8nio/n8n

ENV \
  N8N_BASIC_AUTH_ACTIVE=true \
  N8N_BASIC_AUTH_USER=raremalo \
  N8N_BASIC_AUTH_PASSWORD=PdC9J65TJAVmsGS7wsU% \
  N8N_HOST=0.0.0.0 \
  N8N_PORT=5678 \
  N8N_PROTOCOL=http \
  N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true

EXPOSE 5678
